apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: trueno-backend-database-pvc
spec:
    storageClassName: trueno-backend-database
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 2Gi