apiVersion: v1
kind: Service
metadata:
  name: trueno-backend-database-service
spec:
  ports:
    - protocol: "TCP"
      port: 27017
      targetPort: 27017
  selector:
    component: trueno-backend-database-deployment
  type: LoadBalancer
  loadBalancerIP: ""
